version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Ou uma versão mais recente, como 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the application..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed. Preparing for deployment..."
      # Adicione comandos para copiar artefatos para um bucket S3, se necessário

artifacts:
  files:
    - '**/*'
  base-directory: dist